# Generated by Django 2.1.1 on 2019-04-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPerfumeCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/catagory/')),
            ],
        ),
        migrations.CreateModel(
            name='CarPerfumeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/products/')),
                ('title', models.CharField(default='AERON HOME PERFUME', max_length=200)),
                ('catagory', models.CharField(default='AERON HOME PERFUME', max_length=200)),
                ('quantity1', models.CharField(default='85ml', max_length=200)),
                ('quantity2', models.CharField(default='150ml', max_length=200)),
                ('quantity3', models.CharField(default='1l', max_length=200)),
                ('head_txt1', models.CharField(default='AERON QUALITY PERFUME', max_length=200)),
                ('head_txt2', models.CharField(default='AERON CAR PERFUME', max_length=200)),
                ('description_txt3', models.TextField(default='AERON CAR PERFUME')),
                ('prefume_catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.CarPerfumeCatagory')),
            ],
        ),
        migrations.CreateModel(
            name='HomePerfumeCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/catagory/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePerfumeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/products/')),
                ('title', models.CharField(default='AERON HOME PERFUME', max_length=200)),
                ('catagory', models.CharField(default='AERON HOME PERFUME', max_length=200)),
                ('quantity1', models.CharField(default='85ml', max_length=200)),
                ('quantity2', models.CharField(default='150ml', max_length=200)),
                ('quantity3', models.CharField(default='1l', max_length=200)),
                ('head_txt1', models.CharField(default='AERON QUALITY PERFUME', max_length=200)),
                ('head_txt2', models.CharField(default='AERON CAR PERFUME', max_length=200)),
                ('description_txt3', models.TextField(default='AERON HOME PERFUME')),
                ('prefume_catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.HomePerfumeCatagory')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryCarPerfumeCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='luxurycar/catagory/')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryCarPerfumeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='luxurycar/products/')),
                ('title', models.CharField(default='AERON LUXURY CAR PERFUME', max_length=200)),
                ('catagory', models.CharField(default='AERON LUXURY PERFUME', max_length=200)),
                ('quantity1', models.CharField(default='85ml', max_length=200)),
                ('quantity2', models.CharField(default='150ml', max_length=200)),
                ('quantity3', models.CharField(default='1l', max_length=200)),
                ('head_txt1', models.CharField(default='AERON QUALITY PERFUME', max_length=200)),
                ('head_txt2', models.CharField(default='AERON LUXURY CAR PERFUME', max_length=200)),
                ('description_txt3', models.TextField(default='AERON LUXURY CAR PERFUME')),
                ('prefume_catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.LuxuryCarPerfumeCatagory')),
            ],
        ),
    ]
