# Generated by Django 2.1 on 2019-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='carperfumecatagory',
            name='title',
            field=models.CharField(default='AERON CAR PERFUME', max_length=200),
        ),
        migrations.AddField(
            model_name='homeperfumecatagory',
            name='title',
            field=models.CharField(default='AERON HOME PERFUME', max_length=200),
        ),
        migrations.AddField(
            model_name='luxurycarperfumecatagory',
            name='title',
            field=models.CharField(default='AERON LUXURY CAR PERFUME', max_length=200),
        ),
        migrations.AlterField(
            model_name='carperfumeproducts',
            name='catagory',
            field=models.CharField(default='AERON CAR PERFUME', max_length=200),
        ),
        migrations.AlterField(
            model_name='carperfumeproducts',
            name='title',
            field=models.CharField(default='AERON CAR PERFUME', max_length=200),
        ),
    ]
