# Generated by Django 2.1 on 2019-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
